### ISSUE TITLE
Transitive packages

### ISSUE THREAD

**Issue by jaripekkala** [redsolver/dart_license_checker#1]
Would be nice to get licence info about transitive packages as well. Currently only direct dependencies are noted.

**Comment by redsolver** [comment]
Transitive packages are actively filtered out, because direct dependencies should usually check if their own license is compatible with the dependencies they use. Showing all transitive dependencies too by default also takes quite a lot of space.

**Comment by TheOneWithTheBraid** [comment]
I definitely understand your concerns, @redsolver, but I see an issue in trusting all package maintainers. Maybe a flag providing transitive dependency check might be helpful?

**Comment by redsolver** [comment]
Just added it, you can update using `flutter pub global activate dart_license_checker`. The README contains instructions on how to use the new flag
